### ISSUE TITLE
Some problems with use

### ISSUE THREAD

**Issue by pwfyhao** [nest-cn/nestjs-kafka#1]
![5961651900064_ pic](https://user-images.githubusercontent.com/36838341/167239352-6f13f6cc-f9df-40c6-b84a-6ba85cf83b20.jpg)
![5971651900151_ pic](https://user-images.githubusercontent.com/36838341/167239390-8e77cce3-6013-42e2-a830-d249c62d10bb.jpg)
![5981651900171_ pic](https://user-images.githubusercontent.com/36838341/167239393-5844952b-823f-46b9-9109-8c8254ca3841.jpg)

**Comment by canyuegongzi** [comment]
问题已收到，最近会编译重新发布npm包，如果着急使用，提供两方案参考：
1：ts 编译不要忽略nestjs-kafka目录
2：将nestjs-kafka代码拷贝到工程目录中，以相对路径引用

**Comment by pwfyhao** [comment]
thank!
